import {
  MAX_NUDGE_REASONING_TAIL_CHARS,
  buildLoopBreakerNudge,
  injectHistoryLoopBreaker,
  resetInjectedLoopsForTests,
} from "../src/provider/loop-breaker";
import { NimChatRequest } from "../src/types";
import { createStructuredError } from "../src/api/errors";
import { getSessionEvents, resetSessionLogsForTests } from "../src/shared/logging";

describe("injectHistoryLoopBreaker", () => {
  beforeEach(() => {
    resetInjectedLoopsForTests();
    resetSessionLogsForTests();
  });

  const requestBody: NimChatRequest = {
    model: "test",
    messages: [{ role: "user", content: "hi" }],
  };

  it("injects a breaker when assistant preambles repeat", () => {
    const history = [
      { role: 2, content: [{ value: "Let me fix the formatting issue:" }] },
      { role: 2, content: [{ value: "Let me fix the formatting issue:" }] },
      { role: 2, content: [{ value: "Let me fix the formatting issue:" }] },
    ];
    const result = injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });
    expect(result.messages.at(-1)?.content).toEqual(expect.stringContaining("repeated"));
  });

  it("drops the breaker only on token_limit", () => {
    const history = [
      { role: 2, content: [{ value: "Let me fix the formatting issue:" }] },
      { role: 2, content: [{ value: "Let me fix the formatting issue:" }] },
      { role: 2, content: [{ value: "Let me fix the formatting issue:" }] },
    ];
    const result = injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: () => {
        throw createStructuredError("token_limit", "too big");
      },
    });
    expect(result.messages).toHaveLength(1);
  });

  it("injects a breaker after four repeated preambles instead of aborting the turn", () => {
    const history = Array.from({ length: 4 }, () => ({
      role: 2,
      content: [{ value: "Let me fix the formatting issue:" }],
    }));

    const result = injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });
    expect(result.messages.at(-1)?.content).toEqual(expect.stringContaining("repeated"));
  });

  it("ignores fallback notice headers when checking for repeating preambles", () => {
    const history = [
      {
        role: 2,
        content: [
          {
            value:
              "> ⚡ **NVIDIA NIM Fallback:** Timeout on *GLM 5.3 Flash*. Response generated by *Kimi K3*.\n\nFirst answer.",
          },
        ],
      },
      {
        role: 2,
        content: [
          {
            value:
              "> ⚡ **NVIDIA NIM Fallback:** Timeout on *GLM 5.3 Flash*. Response generated by *Kimi K3*.\n\nSecond answer.",
          },
        ],
      },
      {
        role: 2,
        content: [
          {
            value:
              "> ⚡ **NVIDIA NIM Fallback:** Timeout on *GLM 5.3 Flash*. Response generated by *Kimi K3*.\n\nThird answer.",
          },
        ],
      },
    ];
    const result = injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });
    expect(result.messages).toHaveLength(1);
    expect(result.messages[0]?.content).toBe("hi");
  });

  it("injects a breaker after four repeated tool calls instead of aborting the turn", () => {
    const history = Array.from({ length: 4 }, () => ({
      role: 2,
      content: [
        {
          name: "run_in_terminal",
          input: { command: "npm run compile", mode: "sync" },
        },
      ],
    }));

    const result = injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });
    expect(result.messages.at(-1)?.content).toEqual(expect.stringContaining("identical arguments"));
  });

  it("escalates automatically across sequential turns when the loop persists", () => {
    const history = Array.from({ length: 4 }, () => ({
      role: 2,
      content: [
        {
          name: "run_in_terminal",
          input: { command: "npm run compile", mode: "sync" },
        },
      ],
    }));

    // Turn 1: standard breaker
    const turn1 = injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });
    expect(turn1.messages.at(-1)?.content).toEqual(expect.stringContaining("identical arguments"));
    expect(turn1.messages.at(-1)?.content).not.toEqual(expect.stringContaining("still going"));

    // Turn 2: same history, fresh request body (as Copilot does) -> escalates
    const turn2 = injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });
    expect(turn2.messages.at(-1)?.content).toEqual(expect.stringContaining("still going"));

    // Turn 3: same history, fresh request body -> does not duplicate
    const turn3 = injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });
    expect(turn3.messages).toHaveLength(1);
    expect(turn3.messages[0]?.content).toBe("hi");
  });

  it("logs trippedLine and detector when injecting a preamble breaker", () => {
    const history = [
      { role: 2, content: [{ value: "Let me fix the formatting issue:" }] },
      { role: 2, content: [{ value: "Let me fix the formatting issue:" }] },
      { role: 2, content: [{ value: "Let me fix the formatting issue:" }] },
    ];

    injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });

    const event = getSessionEvents().find(
      (e) =>
        e.label === "repetitionGuard" &&
        typeof e.value === "object" &&
        e.value !== null &&
        (e.value as { action?: unknown }).action === "injectBreaker",
    );
    expect(event).toBeDefined();
    const value = event?.value as Record<string, unknown>;
    expect(value.detector).toBe("preamble");
    expect(value.trippedLine).toBe("let me fix the formatting issue");
    expect(value.escalate).toBe(false);
    expect(value.model).toBe("test-model");
  });

  it("logs trippedLine and detector when injecting a tool-call breaker", () => {
    const history = Array.from({ length: 4 }, () => ({
      role: 2,
      content: [
        {
          name: "run_in_terminal",
          input: { command: "npm run compile", mode: "sync" },
        },
      ],
    }));

    injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });

    const event = getSessionEvents().find(
      (e) =>
        e.label === "repetitionGuard" &&
        typeof e.value === "object" &&
        e.value !== null &&
        (e.value as { action?: unknown }).action === "injectBreaker",
    );
    expect(event).toBeDefined();
    const value = event?.value as Record<string, unknown>;
    expect(value.detector).toBe("toolCallLoop");
    expect(value.trippedLine).toBe('run_in_terminal:{"command":"npm run compile","mode":"sync"}');
    expect(value.escalate).toBe(false);
  });

  it("logs detector and escalate flag on escalation injections", () => {
    const history = Array.from({ length: 4 }, () => ({
      role: 2,
      content: [{ value: "Let me fix the formatting issue:" }],
    }));

    // Turn 1: standard breaker.
    injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });
    // Turn 2: same loop persists -> escalation.
    injectHistoryLoopBreaker({
      requestBody,
      historyMessages: history,
      modelId: "test-model",
      applyBudget: (body) => body,
    });

    const event = getSessionEvents().find(
      (e) =>
        e.label === "repetitionGuard" &&
        typeof e.value === "object" &&
        e.value !== null &&
        (e.value as { action?: unknown }).action === "injectBreakerEscalation",
    );
    expect(event).toBeDefined();
    const value = event?.value as Record<string, unknown>;
    expect(value.detector).toBe("preamble");
    expect(value.trippedLine).toBe("let me fix the formatting issue");
    expect(value.escalate).toBe(true);
  });
});

describe("buildLoopBreakerNudge", () => {
  it("nudges a stalled stream to continue from the partial reply", () => {
    const nudge = buildLoopBreakerNudge("stream_timeout");
    expect(nudge.role).toBe("user");
    expect(nudge.content).toContain("stalled");
  });

  it("never exposes internal marker tags to the model", () => {
    const reasons = [
      "repetition_loop",
      "tool_call_loop",
      "hanging_colon",
      "output_truncated",
      "content_filter",
      "stream_timeout",
      "stream_dropped",
      "reasoning_only",
    ] as const;
    for (const reason of reasons) {
      const plain = buildLoopBreakerNudge(reason);
      const withTail = buildLoopBreakerNudge(reason, { reasoningTail: "Checking the parser." });
      for (const nudge of [plain, withTail]) {
        expect(nudge.content).not.toMatch(/\[NIM_/);
      }
    }
  });

  it("quotes the reasoning tail when a think stalls before any answer", () => {
    const nudge = buildLoopBreakerNudge("stream_timeout", {
      reasoningTail: "So the fix belongs in flush().",
    });
    expect(nudge.content).toContain("still reasoning");
    expect(nudge.content).toContain("So the fix belongs in flush().");
    expect(nudge.content).toContain("without restarting the analysis");
  });

  it("quotes the reasoning tail for a reasoning-only reply", () => {
    const nudge = buildLoopBreakerNudge("reasoning_only", { reasoningTail: "Done editing." });
    expect(nudge.content).toContain("contained only reasoning");
    expect(nudge.content).toContain("Done editing.");
  });

  it("caps the quoted tail and keeps its end", () => {
    const head = "head ".repeat(2000);
    const nudge = buildLoopBreakerNudge("stream_dropped", { reasoningTail: `${head}final step` });
    const content = typeof nudge.content === "string" ? nudge.content : "";
    expect(content).toContain("final step");
    expect(content).toContain("…");
    expect(content.length).toBeLessThan(MAX_NUDGE_REASONING_TAIL_CHARS + 400);
  });

  it("does not quote reasoning for reasons that do not resume a think", () => {
    const nudge = buildLoopBreakerNudge("hanging_colon", { reasoningTail: "secret plan" });
    expect(nudge.content).not.toContain("secret plan");
  });

  it("does not quote a looping think back to the model", () => {
    const nudge = buildLoopBreakerNudge("repetition_loop", {
      reasoningTail: "Wait, let me re-check. Wait, let me re-check.",
      reasoningLoop: true,
    });
    expect(nudge.content).toContain("repeating itself");
    expect(nudge.content).not.toContain("re-check");
  });
});
