// Re-export from new location for backward compatibility
export {
  buildToolCallCanonicalKey,
  getCompletedToolCallKeys,
  getToolSchemaMap,
  hasRequiredToolArguments,
  buildInvalidToolCallFallback,
  buildInvalidToolCallRetryMessage,
  findTrailingTokenPrefixStart,
  findTrailingTokenPrefixStartAny,
  unwrapJsonCodeFence,
  stripKnownControlText,
  findControlTextTerminatorIndex,
  parseDeepSeekTextEmbeddedToolCallContent,
  parseTextEmbeddedToolCalls,
  extractChatRequestContext,
  repairToolArguments,
  isToolCallInput,
} from "./tools/parser";
export type {
  ToolSchema,
  SkippedToolCall,
  ParsedTextToolCall,
  ParsedTextSegmentText,
  ParsedTextSegmentToolCall,
  ParsedTextSegmentInvalidToolCall,
  ParsedTextSegment,
  ParsedTextToolCallResult,
  ChatRequestContext,
} from "./tools/parser";
