import * as vscode from "vscode";
import {
  LanguageModelChatInformation,
  ProvideLanguageModelChatResponseOptions,
  Progress,
  LanguageModelResponsePart,
} from "vscode";
import { NvidiaApiError } from "../api/errors";
import { FallbackConfig } from "../shared/config";
import { calculateSafetyMargin, DEFAULT_MAX_OUTPUT_TOKENS } from "../shared/constants";
import { outputLog } from "../shared/logging";
import { FetchAttemptBudget } from "../shared/fetch-attempt-budget";
import { NormalizedNvidiaModel } from "../models/catalog";

export interface FallbackChainOptions {
  fallbackDepth?: number;
  triedFallbackModelIds?: string[];
  fetchAttemptBudget?: FetchAttemptBudget;
}

export function readFallbackDepth(options: ProvideLanguageModelChatResponseOptions): number {
  const chainOptions = options as ProvideLanguageModelChatResponseOptions & FallbackChainOptions;
  return typeof chainOptions.fallbackDepth === "number" &&
    Number.isFinite(chainOptions.fallbackDepth)
    ? Math.max(0, Math.floor(chainOptions.fallbackDepth))
    : 0;
}

export function readTriedFallbackModelIds(
  options: ProvideLanguageModelChatResponseOptions,
): string[] {
  const chainOptions = options as ProvideLanguageModelChatResponseOptions & FallbackChainOptions;
  return Array.isArray(chainOptions.triedFallbackModelIds)
    ? chainOptions.triedFallbackModelIds.filter(
        (id): id is string => typeof id === "string" && id.length > 0,
      )
    : [];
}

export function readFetchAttemptBudget(
  options: ProvideLanguageModelChatResponseOptions,
): FetchAttemptBudget | undefined {
  return (options as ProvideLanguageModelChatResponseOptions & FallbackChainOptions)
    .fetchAttemptBudget;
}

export function isFallbackEligibleError(
  err: unknown,
  fallbackConfig: FallbackConfig,
  priorDepth: number,
  failingAttemptHasVisibleContent: boolean,
): err is NvidiaApiError {
  const maxChainLength = Math.max(1, fallbackConfig.priorityList.length + 1);
  if (!fallbackConfig.enabled || priorDepth >= maxChainLength || failingAttemptHasVisibleContent) {
    return false;
  }
  return (
    err instanceof NvidiaApiError &&
    ((err.kind === "rate_limited" && fallbackConfig.onRateLimit) ||
      (err.kind === "model_unavailable" && fallbackConfig.onModelUnavailable) ||
      (err.kind === "empty_stream" && fallbackConfig.onEmptyStream) ||
      (err.kind === "timeout" && fallbackConfig.onTimeout) ||
      err.kind === "server_error" ||
      err.kind === "network_error" ||
      err.kind === "token_limit" ||
      err.kind === "context_overflow")
  );
}

export function fallbackCapacityLabel(err: NvidiaApiError): string {
  if (err.kind === "model_unavailable") {
    return "Model unavailable";
  }
  if (err.kind === "empty_stream") {
    return "Empty response";
  }
  if (err.kind === "timeout") {
    return "Timeout";
  }
  if (err.kind === "network_error") {
    return "Network error";
  }
  if (err.kind === "server_error") {
    return "Server error";
  }
  if (err.kind === "context_overflow" || err.kind === "token_limit") {
    return "Context overflow";
  }
  if (err.status === 529) {
    return "Overloaded";
  }
  return "Rate limited";
}

export function buildFallbackModelInfo(
  source: LanguageModelChatInformation,
  fallbackModel: NormalizedNvidiaModel,
): LanguageModelChatInformation {
  const fallbackCapabilities: vscode.LanguageModelChatCapabilities = {
    toolCalling: fallbackModel.supportsTools ? 128 : false,
    imageInput: fallbackModel.supportsVision,
  };
  return {
    ...source,
    id: fallbackModel.id,
    name: fallbackModel.displayName,
    maxInputTokens: Math.max(
      1,
      fallbackModel.contextWindow -
        Math.min(fallbackModel.maxOutputTokens, DEFAULT_MAX_OUTPUT_TOKENS) -
        calculateSafetyMargin(fallbackModel.contextWindow),
    ),
    maxOutputTokens: fallbackModel.maxOutputTokens,
    capabilities: fallbackCapabilities,
  };
}

export function reportFallbackHop(options: {
  err: NvidiaApiError;
  currentModel: LanguageModelChatInformation;
  fallbackModel: NormalizedNvidiaModel;
  fallbackConfig: FallbackConfig;
  progress: Progress<LanguageModelResponsePart>;
}): void {
  const currentName = options.currentModel.name ?? options.currentModel.id;
  const capacityLabel = fallbackCapacityLabel(options.err);

  if (options.fallbackConfig.notifyUser) {
    vscode.window.showInformationMessage(
      `${capacityLabel} on ${currentName}. Falling back to ${options.fallbackModel.displayName}.`,
    );
  }
  outputLog(
    "fallback",
    `${capacityLabel} on ${options.currentModel.id}, falling back to ${options.fallbackModel.id}.`,
  );

  if (options.fallbackConfig.showNoticeInChat) {
    options.progress.report(
      new vscode.LanguageModelTextPart(
        `> ⚡ **NVIDIA NIM Fallback:** ${capacityLabel} on *${currentName}*. Response generated by *${options.fallbackModel.displayName}*.\n\n`,
      ),
    );
  }
}
